import {useState,type FormEvent} from 'react';
import {ArrowRight,Mail,LockKeyhole} from 'lucide-react';
import {useAccount,request} from '@/lib/account';
import {Link} from '@/lib/router';
import {CastArtwork} from './cast-artwork';
import './account-pages.css';
export function LoginPage(){const auth=useAccount();const[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[testLink,setTestLink]=useState(''),[error,setError]=useState(()=>new URLSearchParams(location.search).has('error')?'That link has expired or has already been used. Request a new one below.':'');const requested=new URLSearchParams(location.search).get('next');const next=requested&&(requested==='/create'||requested.startsWith('/create?'))?requested:'/library';
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setTestLink('');try{await request('/api/auth/sign-in/magic-link',{method:'POST',body:JSON.stringify({email:email.trim(),callbackURL:next,errorCallbackURL:'/login?error=expired'})});setSent(true);if(auth.testMode){const d=await request<{url:string|null}>('/api/dev/mailbox',{method:'POST',body:JSON.stringify({email:email.trim()})});setTestLink(d.url||'');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="account-layout"><div className="account-art"><CastArtwork id="pip" name="Pip"/><p>A little adventure.<br/>A place to keep it.</p></div><div className="account-panel"><h1>{auth.user?'Your next chapter awaits.':sent?'Your invitation is ready.':'Make yourself at home.'}</h1><p>Save your ideas, keep your cast together, and pick up where you left off.</p>{auth.user?<Link className="original-cta" to={next}>Open your stories <ArrowRight size={18}/></Link>:<form onSubmit={submit}><label htmlFor="account-email">Email address</label><input id="account-email" type="email" autoComplete="email" value={email} required maxLength={254} onChange={e=>{setEmail(e.target.value);setSent(false);setTestLink('');}} placeholder="you@example.com"/><button className="original-cta" disabled={busy||auth.loading||!auth.available||!auth.emailEnabled}><Mail size={18}/>{busy?'Preparing your link…':sent?'Send a new link':'Send me a sign-in link'}</button>{sent&&<p role="status">{auth.testMode?'Local test: no email was sent. Use the link below to sign in.':'Check your inbox for a link. It expires in 10 minutes and can be used once.'}</p>}{testLink&&<a className="test-signin" href={testLink}>Open local test sign-in <ArrowRight size={16}/></a>}{!auth.loading&&(!auth.available||!auth.emailEnabled)&&<p role="alert">{!auth.available?'The account server is unavailable. Please try again shortly.':'Email sign-in is not configured on this installation yet.'}</p>}{error&&<p role="alert" className="account-error">{error}</p>}<small><LockKeyhole size={14}/> No password to remember. Your drafts stay private.</small>{auth.testMode&&<small>Local development mode · Email delivery will be connected with Resend.</small>}</form>}</div></section>;
}
export {LibraryPage} from './library-page';

