import {StudioSkeleton} from './studio-skeleton';
import {useEffect,useState,type FormEvent} from 'react';
import {CheckCircle2,ArrowLeft,ExternalLink} from 'lucide-react';
import {request,useAccount} from '@/lib/account';
import {Link} from '@/lib/router';
import './connections-page.css';
type Provider='fal'|'higgsfield'|'openrouter';
const SERVICES:{id:Provider;title:string;description:string;url:string}[]=[{id:'fal',title:'fal',description:'Used for Budget and Recommended films. Charges go to your fal balance.',url:'https://fal.ai/dashboard/keys'},{id:'higgsfield',title:'Higgsfield',description:'An alternative video provider with a separate API balance.',url:'https://console.higgsfield.ai'},{id:'openrouter',title:'Story writer',description:'Optional AI script writing through OpenRouter. Writing your own script is free.',url:'https://openrouter.ai/settings/keys'}];
export function ConnectionsPage(){
 const auth=useAccount(),[providers,setProviders]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Provider|null>(null),[keys,setKeys]=useState<Record<Provider,string>>({fal:'',higgsfield:'',openrouter:''}),[secret,setSecret]=useState('');
 async function refresh(){setLoading(true);setError('');try{const result=await request<{providers:{provider:string}[]}>('/api/studio/keys');setProviders(result.providers.map(p=>p.provider));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(auth.user)void refresh();},[auth.user]);
 async function save(e:FormEvent,provider:Provider){e.preventDefault();setBusy(true);setError('');setMessage('');try{await request('/api/studio/keys',{method:'PUT',body:JSON.stringify({provider,key:keys[provider].trim(),...(provider==='higgsfield'?{secret:secret.trim()}:{})})});setKeys(v=>({...v,[provider]:''}));setSecret('');setEditing(null);await refresh();setMessage('Key saved. Model access will be checked when you generate.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(provider:Provider){setBusy(true);setError('');setMessage('');try{await request('/api/studio/keys',{method:'DELETE',body:JSON.stringify({provider})});await refresh();setMessage('Key removed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function cancel(){setEditing(null);setKeys({fal:'',higgsfield:'',openrouter:''});setSecret('');}
 const renderService=(service:typeof SERVICES[number])=>{const saved=providers.includes(service.id),open=editing===service.id;return <section className="connection-row" key={service.id} aria-label={service.title+' connection'}><div className="connection-info"><div className="connection-title"><h2>{service.title}</h2><span className={saved?'key-status saved':'key-status'}>{saved?<><CheckCircle2 size={17}/>Key saved</>:'Not connected'}</span></div><p>{service.description}</p>{saved&&<p className="connection-detail">Your key is stored securely. You don’t need to enter it again.<br/>Model access has not been verified here.</p>}<a className="connection-external" href={service.url} target="_blank" rel="noreferrer">{saved?'Manage provider account':'Get an API key'}<ExternalLink size={14}/></a></div><div className="connection-controls">{open?<form onSubmit={e=>void save(e,service.id)}><label htmlFor={'key-'+service.id}>{saved?'Replacement ':''}{service.id==='higgsfield'?'API key ID':'API key'}</label><input id={'key-'+service.id} type="password" autoComplete="new-password" value={keys[service.id]} onChange={e=>setKeys(v=>({...v,[service.id]:e.target.value}))} required minLength={8} maxLength={512}/>{service.id==='higgsfield'&&<><label htmlFor="higgsfield-secret">API key secret</label><input id="higgsfield-secret" type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} required minLength={8} maxLength={512}/></>}<div className="connection-actions"><button className="connection-primary" disabled={busy}>Save key</button><button type="button" disabled={busy} onClick={cancel}>Cancel</button></div></form>:<div className="connection-actions"><button className={saved?'':'connection-primary'} disabled={busy} onClick={()=>{cancel();setEditing(service.id);}}>{saved?'Change key':'Connect'}</button>{saved&&<button className="connection-remove" disabled={busy} onClick={()=>void remove(service.id)}>Disconnect</button>}</div>}</div></section>;};
 if(auth.loading)return <StudioSkeleton kind="connections"/>;
 if(!auth.user)return <section className="connections-workspace"><h1>Connections</h1><p>Sign in to manage the keys for your private workspace.</p><Link to="/login">Sign in</Link></section>;
 return <section className="connections-workspace"><Link className="connections-back" to="/library"><ArrowLeft size={16}/>My stories</Link><header><h1>Connections</h1><p>Manage the API key used to make your films.</p></header><p className="connection-account">Workspace for {auth.user.email}</p>{message&&<p role="status" className="connection-notice">{message}</p>}{error&&<div role="alert" className="connection-notice"><p>{error}</p><button onClick={()=>void refresh()}>Refresh connection status</button></div>}{loading?<StudioSkeleton kind="connections"/>:<div className="connection-list">{renderService(SERVICES[0])}<details className="other-connections"><summary>Other connections <span>Higgsfield and optional story writer</span></summary>{SERVICES.slice(1).map(renderService)}</details></div>}<footer><p>Saved keys are encrypted on the server and are never displayed here. Generation uses your provider balance.</p><Link to="/create" className="connection-primary">Create a story</Link></footer></section>;
}

