import './legal-page.css';
const independence='TheHiggsField is an independent service. We are not affiliated with, owned by, operated by, sponsored by, or endorsed by Higgsfield.ai. An optional Higgsfield integration does not imply a partnership. Provider names and trademarks belong to their respective owners.';
export function LegalPage({kind}:{kind:'terms'|'privacy'}){return <article className="studio-legal"><header><h1>{kind==='terms'?'Terms of use':'Privacy policy'}</h1><p>Last updated: September 26, 2026</p></header><aside aria-label="Independent service disclosure"><h2>A separate, independent service</h2><p>{independence}</p></aside>{kind==='terms'?<>
<section><h2>Using TheHiggsField</h2><p>You are responsible for your account and the content you submit. Only upload material you have permission to use. Do not use the service for unlawful activity, rights infringement, or deceptive impersonation. Review generated content before using or sharing it.</p></section>
<section><h2>Connected providers and costs</h2><p>Generation uses your connected provider account, including fal or Higgsfield when selected. Estimated costs are shown before rendering; final provider charges may differ. Additional renders may incur additional charges. Provider billing, credits, refunds, and availability are governed by the provider’s terms. We do not manage Higgsfield.ai customer accounts.</p></section>
<section><h2>Your content and generated results</h2><p>You retain the rights you hold in your uploads. You authorize the processing needed to provide the features you choose, including sending generation inputs to your selected provider. AI outputs can be inaccurate or inconsistent. We do not guarantee originality, rights clearance, or any particular creative result. Keep copies of important work.</p></section>
<section><h2>Saved work and deletion</h2><p>Drafts, uploaded characters, and generation records are saved to your workspace. Deleting a draft does not delete completed films or cancel provider requests. Removing a connection does not close your provider account or reverse charges already incurred.</p></section>
<section><h2>Questions and updates</h2><p>Use our <a href="/contact">contact page</a> for service or privacy questions. These terms may change as the service develops; the date above identifies this version.</p></section>
</>:<>
<section><h2>Account and workspace information</h2><p>We store account and session information to support sign-in. Your use of the studio may also save story drafts, scripts, uploaded characters, generation requests, results, and connection settings. Private workspace information is associated with your account.</p></section>
<section><h2>Provider credentials</h2><p>Saved provider credentials are encrypted at rest. The server decrypts them to make requests you authorize; this is not end-to-end encryption. Saved secrets are not returned to the browser. You can replace or remove a provider connection from Connections.</p></section>
<section><h2>Information sent to providers</h2><p>When you generate content, the selected provider receives the credentials and inputs required for the request, such as prompts, scripts, and character reference images. Providers such as fal and Higgsfield process those requests under their own terms and privacy policies. This is TheHiggsField’s policy, not Higgsfield.ai’s privacy policy.</p></section>
<section><h2>Hosting, sign-in, and browser storage</h2><p>Our hosting server stores workspace data. Cloudflare provides traffic proxy and security services. A configured email provider delivers sign-in links; Google processes Google sign-in when enabled. Session cookies maintain sign-in, and browser storage remembers preferences and local work.</p></section>
<section><h2>Contact and waitlist submissions</h2><p>Contact forms store the information you submit, submission time, consent version, and an abuse-prevention network identifier. Waitlist forms store your email and signup information. These submissions are not sent to AI generation providers. Do not include passwords or API keys in contact messages.</p></section>
<section><h2>Your controls</h2><p>You can delete story drafts and remove saved provider connections in the studio. Deleting a draft does not delete separately stored films or uploads. For requests concerning your personal information, use the <a href="/contact">contact page</a> and select Privacy or data request. Copies already sent to providers remain subject to their policies. Clearing browser storage removes local preferences and may remove unsynced work.</p></section>
</>}<nav><a href={kind==='terms'?'/privacy':'/terms'}>{kind==='terms'?'Privacy policy':'Terms of use'}</a><a href="/">Back to home</a></nav></article>}
