import type {ResearchAssessment} from '../../lib/ugc-project';
const stages=[{key:'Brief',label:'Your idea',hint:'A few true details',icon:'✦'},{key:'References',label:'Discover',hint:'Find your inspiration',icon:'◎'},{key:'Creative',label:'Shape the story',hint:'Research, then decide',icon:'✳'},{key:'Edit & export',label:'Make & save',hint:'Your finished creation',icon:'↗'}];
export function StudioJourney({step,product,referenceCount,sceneCount,busy,onStep,onContinue,saved}:{step:string;product:string;referenceCount:number;sceneCount:number;busy:boolean;onStep:(step:string)=>void;onContinue:()=>void;saved:string}){
 const index=stages.findIndex(s=>s.key===step);if(index<0)return null;
 const next=['Save idea & discover','Save research & review','Save story & open editor','Save this project'][index];
 const summary=index===0?'Start with what your product really does. We’ll help you turn it into a story.':index===1?`${referenceCount} references selected. Find a useful structure, then make it your own.`:index===2?'Let Jev check the evidence. Choose an opening that fits your story.':`${sceneCount} scenes in your edit. Add your footage, review the result, and export.`;
 return <section className="studio-journey" aria-label="Your creative journey"><div className="journey-heading"><div><p className="ugc-eyebrow">FROM A SMALL IDEA TO SOMETHING WORTH WATCHING</p><p>{summary}</p></div><span className="journey-save" role="status">{saved||'Draft on this device · Save to keep it in your workspace'}</span></div><nav className="journey-stages" aria-label="Creation stages">{stages.map((stage,i)=><button key={stage.key} disabled={busy} aria-current={i===index?'step':undefined} onClick={()=>onStep(stage.key)}><span className="journey-icon" aria-hidden="true">{stage.icon}</span><span><strong>{stage.label}</strong><small>{stage.hint}</small></span></button>)}</nav><div className="journey-footer"><span>Step {index+1} of 4 · You can revisit any step</span><button className="journey-next" disabled={busy||!product.trim()} onClick={onContinue}>{busy?'Working…':next} <span aria-hidden="true">→</span></button></div></section>;
}
const names:Record<string,string>={audienceFit:'Does it fit your audience?',evidenceReadiness:'Do we have enough to create?',hookApproach:'How should the story open?'};
const answers:Record<string,string>={relevant:'A relevant direction',partial:'Some useful connections',insufficient:'Bring a little more evidence',ready:'Ready for a first storyboard',needs_detail:'Add the missing details',demonstration:'Show the product in action',question:'Open with a useful question',process:'Show how it happens',need_context:'Tell us a little more',not_reported:'No answer returned'};
export function ResearchReview({assessment,onResearch,stale=false}:{stale?:boolean;assessment:ResearchAssessment;onResearch:()=>void}){
 const needsMore=assessment.answers.some(a=>a.id==='evidenceReadiness'&&['insufficient','needs_detail','not_reported'].includes(a.choice));
 return <section className="research-review">{stale&&<p role="status" className="ugc-notice">Your brief or references changed. Rerun Jev before using this assessment; it is excluded from new AI treatments until refreshed.</p>}<div className="review-heading"><div><p className="ugc-eyebrow">A SECOND PAIR OF EYES · JEV</p><h2>Your research.<br/><em>A clearer next move.</em></h2></div><span className="review-snapshot">Saved {new Date(assessment.assessedAt).toLocaleString()}<br/>Rerun after editing your brief or sources.</span></div><div className="review-cards">{assessment.answers.map(a=><article key={a.id}><p>{names[a.id]||a.id}</p><h3>{answers[a.choice]||a.choice.replaceAll('_',' ')}</h3>{a.confidence!==null?<><meter min={0} max={1} value={a.confidence} aria-label={(names[a.id]||a.id)+' decision confidence'}/><small>{Math.round(a.confidence*100)}% confidence in this answer</small></>:<small>Confidence not reported</small>}</article>)}</div><p className="ugc-fine">{assessment.meaning}</p>{needsMore&&<div className="review-next"><p><strong>A stronger source will help.</strong><br/>Add a transcript, your scene observations, or clearer product facts before generating footage.</p><button onClick={onResearch}>Strengthen my research →</button></div>}<details><summary>See the sources supplied to Jev ({assessment.sourceUrls.length})</summary><p className="ugc-fine">These sources were context for the assessment, not proof of why a video performed.</p>{assessment.sourceUrls.map((url,i)=><p key={url}><a href={url} target="_blank" rel="noreferrer">Source {i+1} ↗</a></p>)}</details></section>;
}
