import {randomUUID,createHash} from 'node:crypto';
const hash=s=>createHash('sha256').update(s).digest('hex');
export function createWorkspaces(db){db.exec(`CREATE TABLE IF NOT EXISTS workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS workspace_members(workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,PRIMARY KEY(workspace_id,user_id));`);
function list(userId){return db.prepare('SELECT w.id,w.name,m.role FROM workspaces w JOIN workspace_members m ON w.id=m.workspace_id WHERE m.user_id=? ORDER BY w.created_at').all(userId);}
function ensure(userId){let rows=list(userId);if(!rows.length){const id=userId==='owner'?'owner':'personal-'+hash(userId).slice(0,24);db.prepare('INSERT OR IGNORE INTO workspaces VALUES (?,?,?)').run(id,'My workspace',Date.now());db.prepare('INSERT OR IGNORE INTO workspace_members VALUES (?,?,?)').run(id,userId,'owner');rows=list(userId);}return rows;}
function scope(req,userId){const rows=ensure(userId);const requested=req.headers['x-workspace-id'];return requested?rows.find(w=>w.id===requested):rows[0];}
async function handle(req,res,url,userId,origin){const reply=(code,data)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};if(!userId){reply(401,{error:'Sign in first.'});return;}if(req.method!=='GET'&&req.headers.origin!==origin){reply(403,{error:'Invalid request origin.'});return;}try{if(url.pathname==='/api/workspaces'&&req.method==='GET'){reply(200,{workspaces:ensure(userId)});return;}let text='';for await(const c of req){text+=c;if(text.length>2048){reply(413,{error:'Request too large.'});return;}}const data=text?JSON.parse(text):{};
if(url.pathname==='/api/workspaces'&&req.method==='POST'){if(typeof data.name!=='string'||!data.name.trim()||data.name.length>80){reply(400,{error:'Enter a workspace name up to 80 characters.'});return;}if(ensure(userId).filter(w=>w.role==='owner').length>=20){reply(409,{error:'You can own up to 20 workspaces.'});return;}const id=randomUUID();db.prepare('INSERT INTO workspaces VALUES (?,?,?)').run(id,data.name.trim(),Date.now());db.prepare('INSERT INTO workspace_members VALUES (?,?,?)').run(id,userId,'owner');reply(200,{workspace:{id,name:data.name.trim(),role:'owner'}});return;}
const w=scope(req,userId);if(!w||w.role!=='owner'){reply(403,{error:'Only the workspace owner can manage members.'});return;}
if(url.pathname==='/api/workspaces/members'&&req.method==='GET'){reply(200,{members:db.prepare("SELECT m.user_id,m.role,COALESCE(u.email,'Instance administrator') AS email FROM workspace_members m LEFT JOIN platform_users u ON m.user_id=u.id WHERE m.workspace_id=?").all(w.id)});return;}
if(url.pathname==='/api/workspaces/members'&&req.method==='POST'){if(!['editor','viewer'].includes(data.role)||typeof data.email!=='string'){reply(400,{error:'Choose an existing account email and editor or viewer role.'});return;}const user=db.prepare('SELECT id FROM platform_users WHERE email=?').get(data.email.trim().toLowerCase());if(!user){reply(404,{error:'That person must sign in to this instance before you can add them.'});return;}if(user.id===userId){reply(400,{error:'You cannot change your own owner role.'});return;}db.prepare('INSERT INTO workspace_members VALUES (?,?,?) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=excluded.role').run(w.id,user.id,data.role);reply(200,{saved:true});return;}
if(url.pathname==='/api/workspaces/members'&&req.method==='DELETE'){if(data.userId===userId){reply(400,{error:'The owner cannot remove themselves.'});return;}db.prepare("DELETE FROM workspace_members WHERE workspace_id=? AND user_id=? AND role!='owner'").run(w.id,String(data.userId));reply(200,{removed:true});return;}reply(404,{error:'Not found.'});}catch{reply(400,{error:'Could not update this workspace.'});}}
return{ensure,scope,handle};}
