import {z} from "zod";
export const goals=["Product launch","Feature demo","Tutorial","Product update","Before and after","UGC ad","Brand film","Social story"] as const;
export const sceneSchema=z.object({id:z.string().uuid(),title:z.string().max(100),showCaption:z.boolean().optional(),mediaFit:z.enum(["cover","contain"]).optional(),caption:z.string().max(240),narration:z.string().max(1500),visual:z.string().max(2000),seconds:z.number().min(1).max(30),mediaId:z.string().max(100).optional(),trim:z.number().min(0).max(3600).default(0),zoom:z.number().min(1).max(2).default(1),focusX:z.number().min(0).max(1).default(.5),focusY:z.number().min(0).max(1).default(.5)}).strict();
export const projectSchema=z.object({id:z.string().uuid(),name:z.string().min(1).max(100),product:z.string().max(100),url:z.string().max(2048),audience:z.string().max(300),benefit:z.string().max(1000),details:z.string().max(12000),goal:z.enum(goals),tone:z.enum(["Clear & confident","Playful","Minimal","Bold"]),cta:z.string().max(140),accent:z.string().regex(/^#[a-f0-9]{6}$/i),background:z.string().regex(/^#[a-f0-9]{6}$/i),format:z.enum(["16:9","9:16","1:1","4:3","3:4","21:9"]),exportResolution:z.enum(["480p","720p","1080p"]).optional(),font:z.enum(["Manrope","Arial","Georgia"]).optional(),hook:z.number().int().min(0).max(2),scenes:z.array(sceneSchema).max(12),logoId:z.string().max(100).optional(),voiceoverId:z.string().max(100).optional(),musicId:z.string().max(100).optional(),includeClipAudio:z.boolean().optional(),voiceoverVolume:z.number().min(0).max(1).optional(),musicVolume:z.number().min(0).max(1).optional(),clipVolume:z.number().min(0).max(1).optional(),updatedAt:z.number(),revision:z.number().int().min(0).default(0)}).strict();
export type LaunchProject=z.infer<typeof projectSchema>;export type Scene=z.infer<typeof sceneSchema>;
export function newProject():LaunchProject{return{id:crypto.randomUUID(),name:"Untitled launch",product:"",url:"",audience:"",benefit:"",details:"",goal:"Product launch",tone:"Clear & confident",cta:"Try it today",accent:"#ff784f",background:"#261735",format:"16:9",hook:0,scenes:[],updatedAt:Date.now(),revision:0};}
export function hooks(p:LaunchProject){const name=p.product||"Your product",benefit=p.benefit||"make your next project simpler";if(p.tone==="Minimal")return[`${name}. ${benefit}`,`Less friction. Meet ${name}.`,`One workflow. ${name}.`];if(p.tone==="Playful")return[`Say hello to ${name}. Your next little productivity win.`,`Plot twist: ${name} can help you ${benefit}.`,`A little less busywork. A little more ${name}.`];if(p.tone==="Bold")return[`Make room for ${name}.`,`${benefit.charAt(0).toUpperCase()+benefit.slice(1)}. Start with ${name}.`,`Your next move: ${name}.`];return[`Meet ${name}. ${benefit.charAt(0).toUpperCase()+benefit.slice(1)}`,`Still doing it the hard way? ${name} offers another approach.`,`Here is how ${name} helps ${p.audience||"builders"} ${benefit.charAt(0).toLowerCase()+benefit.slice(1)}.`];}
export function makeScenes(p:LaunchProject):Scene[]{const feature=p.details.split(/\n|(?<=[.!?])\s+/).map(x=>x.trim().slice(0,600)).filter(Boolean).slice(0,3);const steps=p.goal==="Tutorial"?["Start here","Follow the workflow","Check the result"]:p.goal==="Before and after"?["The old way","A better workflow","The difference"]:p.goal==="Product update"?["What changed","See it in action","Try the update"]:["The problem","Meet the product","See it in action"];const lines=[hooks(p)[p.hook],...steps.map((title,i)=>feature[i]||[p.benefit||"Describe the problem your product solves.",`Show the core workflow in ${p.product||"your product"}.`,`Explain what changes for ${p.audience||"your audience"}.`][i]),p.cta];return lines.map((line,i)=>({id:crypto.randomUUID(),title:i===0?"The hook":i===4?"The invitation":steps[i-1],caption:line.slice(0,180),narration:line,visual:i===0?"Open with your clearest product moment.":i===4?"Close on your product and a specific next step.":"Use real product footage to demonstrate this point.",seconds:i===0?4:i===4?4:6,trim:0,zoom:1,focusX:.5,focusY:.5}));}
export function captions(p:LaunchProject){let time=0;const stamp=(seconds:number)=>{const ms=Math.round(seconds*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`;};return p.scenes.map((s,i)=>{const start=time;time+=s.seconds;return `${i+1}\n${stamp(start)} --> ${stamp(time)}\n${s.caption.replace(/\r?\n/g,' ')}\n`;}).join('\n');}
export function launchCopy(p:LaunchProject){return `${p.product||p.name}\n\n${hooks(p)[p.hook]}\n\n${p.details}\n\n${p.cta}${p.url?' → '+p.url:''}`;}
export function projectMarkdown(p:LaunchProject){return `# ${p.name}\n\nAudience: ${p.audience}\nGoal: ${p.goal}\nTone: ${p.tone}\n\n${p.scenes.map((s,i)=>`## ${i+1}. ${s.title} (${s.seconds}s)\n${s.narration}\n\nVisual: ${s.visual}`).join('\n\n')}\n\n## Launch post\n${launchCopy(p)}`;}
