import {treatmentDraftSchema} from './creative-treatment';
import {z} from 'zod';
import {newProject,projectSchema,type LaunchProject} from './launch-project';
export const categories=['Product brand','SaaS / app','Service business','Creator / educator'] as const;
export const referenceSchema=z.object({id:z.string(),url:z.string().startsWith('https://').max(2048),sku:z.string(),found:z.boolean(),text:z.string().max(16000),metrics:z.record(z.string(),z.number().nonnegative()),coverage:z.string(),autoCaptions:z.boolean().nullable(),retrievedAt:z.number(),costUsd:z.number().nullable()});
export type Evidence=z.infer<typeof referenceSchema>;
export const assessmentSchema=z.object({assessedAt:z.number(),sourceUrls:z.array(z.string().startsWith('https://').max(2048)).max(10),answers:z.array(z.object({id:z.string(),choice:z.string(),confidence:z.number().min(0).max(1).nullable()})).max(10),meaning:z.string()});
export type ResearchAssessment=z.infer<typeof assessmentSchema>;
export const uploadedReferenceSchema=z.object({id:z.string().uuid(),assetId:z.string().uuid(),name:z.string().max(200),type:z.string().max(100),purpose:z.enum(['product','character','brand','style']),notes:z.string().max(1200),approved:z.boolean(),frameIds:z.array(z.string().uuid()).max(3).optional(),analysisId:z.string().uuid().optional(),summary:z.string().max(6000).optional(),coverage:z.string().max(500).optional()});
export type UploadedReference=z.infer<typeof uploadedReferenceSchema>;
export const ugcSchema=z.object({targetSeconds:z.number().int().min(5).max(180).optional(),generationSettings:z.object({model:z.string(),duration:z.number().int().min(1).max(30),resolution:z.string(),audio:z.boolean(),budget:z.string().max(12),preference:z.enum(['economy','balanced'])}).optional(),generationJobs:z.array(z.object({jobId:z.string(),sceneId:z.string().uuid(),createdAt:z.number()})).max(200).optional(),treatment:treatmentDraftSchema.optional(),treatmentSource:z.string().max(100000).optional(),brand:z.object({id:z.string(),name:z.string().max(100),description:z.string().max(2000),guidelines:z.string().max(3000)}).optional(),generationImageIds:z.array(z.string().uuid()).max(3).optional(),uploadedReferences:z.array(uploadedReferenceSchema).max(12).optional(),researchAssessment:assessmentSchema.optional(),assessmentSource:z.string().max(64).optional(),project:projectSchema,category:z.enum(categories),references:z.array(referenceSchema).max(10),hooks:z.array(z.string().max(200)).length(3),notes:z.string().max(6000),results:z.array(z.object({id:z.string(),label:z.string().max(100),views:z.number().nonnegative(),clicks:z.number().nonnegative(),conversions:z.number().nonnegative()})).max(30)});
export type UGC=z.infer<typeof ugcSchema>;
export function newUGC():UGC{return {project:{...newProject(),name:'My next creative',format:'9:16'},category:'Product brand',references:[],hooks:['','',''],notes:'',results:[]};}
export function starterHooks(p:LaunchProject,category:UGC['category']):string[]{const name=p.product||'your product';return category==='SaaS / app'?[`Here is ${name}, in one real workflow.`,`Still spending time on ${p.audience||'the same task'}?`,`What happens between the idea and the finished result?`]:category==='Service business'?[`Here is what working with ${name} looks like.`,`Before you choose your next ${p.product||'service'}, ask this.`,`One question we hear from ${p.audience||'our customers'}.`]:category==='Creator / educator'?[`Here is one way to approach ${p.product||'this topic'}.`,`Start with this, before you try the complicated version.`,`Let me show you the process behind ${name}.`]:[`A closer look at ${name}.`,`A small detail that makes ${name} worth a look.`,`What does ${name} actually do?`];}
export function buildUGC(p:LaunchProject,hook:string,format='demo'):LaunchProject{const lines=p.details.split(/\n/).map(x=>x.trim()).filter(Boolean);const titles=format==='problem'?['The question','The friction','The product','The demonstration','The next step']:format==='story'?['The opening','Why it exists','How it works','The detail','The invitation']:['The hook','Show the product','Show the benefit','Prove the detail','The invitation'];const narration=[hook,lines[0]||`Meet ${p.product||'the product'}.`,p.benefit||'Add the specific benefit you can demonstrate.',lines[1]||'Show the actual process, product, or result without inventing claims.',p.cta];return {...p,scenes:titles.map((title,i)=>({id:crypto.randomUUID(),title,caption:narration[i].slice(0,140),narration:narration[i].slice(0,600),visual:['Open with owned product footage or a clear screen recording.','Show the real product in context. Keep packaging and interface accurate.','Demonstrate the benefit with footage you own.','Show the evidence for this claim. Avoid simulated testimonials.','Close on the product and the next step.'][i],seconds:5,trim:0,zoom:1,focusX:.5,focusY:.5})),updatedAt:Date.now()};}
