import {downloadProviderMedia} from './provider-media.mjs';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {mkdir,open,unlink,stat,readFile} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {pipeline} from 'node:stream/promises';
import path from 'node:path';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
const execute=promisify(execFile);
const allowed=new Set(['image/png','image/jpeg','image/webp','video/mp4','video/webm','audio/mpeg','audio/wav','audio/x-wav','audio/webm']);
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
export function validMedia(bytes,type){if(type==='image/png')return bytes.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex'));if(type==='image/jpeg')return bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(type==='image/webp')return bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP';if(type==='video/mp4')return bytes.toString('ascii',4,8)==='ftyp';if(type.endsWith('webm'))return bytes.subarray(0,4).equals(Buffer.from('1a45dfa3','hex'));if(type==='audio/mpeg')return bytes.toString('ascii',0,3)==='ID3'||bytes[0]===255&&(bytes[1]&224)===224;return ['audio/wav','audio/x-wav'].includes(type)&&bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WAVE';}
export async function convertMp4(input,output,type,{ffmpeg='ffmpeg',ffprobe='ffprobe'}={}){let metadata;try{const result=await execute(ffprobe,['-v','error','-protocol_whitelist','file,pipe','-f',type==='video/webm'?'matroska':'mov','-show_streams','-show_format','-of','json',input],{timeout:15000,maxBuffer:1048576,windowsHide:true});metadata=JSON.parse(result.stdout);}catch{throw Error('Cannot inspect source media. Install FFprobe and use a valid MP4 or WebM.');}const video=metadata.streams?.find(s=>s.codec_type==='video'),duration=Number(metadata.format?.duration);if(!video||!Number.isFinite(duration)||duration<=0||duration>180||video.width*video.height>9000000)throw Error('MP4 export supports video up to 180 seconds and 9 megapixels.');return new Promise((resolve,reject)=>{const args=['-hide_banner','-loglevel','error','-nostdin','-threads','1','-protocol_whitelist','file,pipe','-f',type==='video/webm'?'matroska':'mov','-i',input,'-t','180','-map','0:v:0','-map','0:a:0?','-vf','scale=w=min(4096\\,iw):h=min(4096\\,ih):force_original_aspect_ratio=decrease:force_divisible_by=2','-c:v','libx264','-preset','veryfast','-crf','22','-pix_fmt','yuv420p','-threads','1','-c:a','aac','-b:a','128k','-movflags','+faststart','-fs','52428800','-f','mp4',output];const child=spawn(ffmpeg,args,{stdio:['ignore','ignore','pipe'],windowsHide:true});let stderr='';child.stderr.on('data',chunk=>{stderr=(stderr+chunk).slice(-2000);});const timer=setTimeout(()=>child.kill('SIGKILL'),180000);child.on('error',()=>{clearTimeout(timer);reject(Error('MP4 converter is not installed or could not start.'));});child.on('exit',code=>{clearTimeout(timer);code===0?resolve():reject(Error('MP4 conversion failed. Check the source format and duration.'));});});}
export function createMedia(db,{dataDir,origin,workspaces,authorized,converter=convertMp4,downloader=downloadProviderMedia,maxBytes=25*1048576,quotaBytes=500*1048576}){
 const root=path.join(dataDir,'media');const ready=mkdir(root,{recursive:true,mode:0o700});
 db.exec(`CREATE TABLE IF NOT EXISTS studio_media(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL,size INTEGER NOT NULL,state TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS studio_media_shares(token_hash TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,asset_id TEXT NOT NULL,expires_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS studio_media_sources(workspace_id TEXT NOT NULL,job_id TEXT NOT NULL,asset_id TEXT NOT NULL,PRIMARY KEY(workspace_id,job_id));CREATE INDEX IF NOT EXISTS media_workspace ON studio_media(workspace_id);CREATE TABLE IF NOT EXISTS studio_exports(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,source_id TEXT NOT NULL,state TEXT NOT NULL,asset_id TEXT,error TEXT,created_at INTEGER NOT NULL,UNIQUE(workspace_id,source_id));`);
 db.exec('CREATE TABLE IF NOT EXISTS studio_media_metadata(asset_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,tags TEXT NOT NULL,archived INTEGER NOT NULL DEFAULT 0)');
 // A process restart cannot safely continue a half-written file. No provider call is retried.
 db.exec("DELETE FROM studio_media WHERE state IN ('uploading','converting'); UPDATE studio_exports SET state='failed',error='Server restarted during conversion. Original media is retained.' WHERE state='running'");
 let uploads=0,running=false,closed=false;const locks=new Set();
 const file=id=>{if(!uuid.test(id))throw Error('Invalid media ID');return path.join(root,id);};
 const usage=wid=>Number(db.prepare('SELECT COALESCE(SUM(size),0) AS n FROM studio_media WHERE workspace_id=?').get(wid).n);
 async function work(){if(running||closed)return;const job=db.prepare("SELECT * FROM studio_exports WHERE state='queued' ORDER BY created_at LIMIT 1").get();if(!job)return;running=true;let outputId;try{await ready;db.prepare("UPDATE studio_exports SET state='running' WHERE id=?").run(job.id);const source=db.prepare("SELECT * FROM studio_media WHERE id=? AND workspace_id=? AND state='ready'").get(job.source_id,job.workspace_id);if(!source)throw Error('Source media is unavailable.');if(usage(job.workspace_id)+50*1048576>quotaBytes)throw Error('Free at least 50 MB of workspace storage before converting.');outputId=randomUUID();db.prepare('INSERT INTO studio_media VALUES (?,?,?,?,?,?,?)').run(outputId,job.workspace_id,source.name.replace(/\.[^.]+$/,'')+'.mp4','video/mp4',50*1048576,'converting',Date.now());await converter(file(source.id),file(outputId),source.type);const size=(await stat(file(outputId))).size;if(size<=0||size>50*1048576)throw Error('Invalid converted output size.');db.prepare("UPDATE studio_media SET size=?,state='ready' WHERE id=?").run(size,outputId);db.prepare("UPDATE studio_exports SET state='completed',asset_id=?,error=NULL WHERE id=?").run(outputId,job.id);}catch(e){if(outputId){await unlink(file(outputId)).catch(()=>{});db.prepare('DELETE FROM studio_media WHERE id=?').run(outputId);}db.prepare("UPDATE studio_exports SET state='failed',error=? WHERE id=?").run(e.message,job.id);}finally{running=false;if(!closed)setImmediate(()=>void work());}}
 const timer=setInterval(()=>void work(),1000);timer.unref();
 const reply=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
 async function handle(req,res,url){const user=authorized(req);if(!user)return reply(res,401,{error:'Sign in first.'});const workspace=workspaces.scope(req,user);if(!workspace)return reply(res,403,{error:'Workspace access denied.'});const wid=workspace.id;if(!['GET','HEAD'].includes(req.method)){if(req.headers.origin!==origin)return reply(res,403,{error:'Invalid request origin.'});if(workspace.role==='viewer')return reply(res,403,{error:'Viewers cannot modify media.'});}
 try{await ready;
 if(url.pathname==='/api/media'&&req.method==='GET')return reply(res,200,{assets:db.prepare("SELECT m.id,m.name,m.type,m.size,m.created_at,COALESCE(md.tags,'[]') AS tags,COALESCE(md.archived,0) AS archived,CASE WHEN EXISTS(SELECT 1 FROM studio_media_sources s WHERE s.asset_id=m.id AND s.workspace_id=m.workspace_id) THEN 'generated' WHEN EXISTS(SELECT 1 FROM studio_exports e WHERE e.asset_id=m.id AND e.workspace_id=m.workspace_id) THEN 'export' ELSE 'upload' END AS origin FROM studio_media m LEFT JOIN studio_media_metadata md ON md.asset_id=m.id AND md.workspace_id=m.workspace_id WHERE m.workspace_id=? AND m.state='ready' ORDER BY m.created_at DESC LIMIT 200").all(wid).map(a=>({...a,tags:JSON.parse(a.tags),archived:Boolean(a.archived)})),usedBytes:usage(wid),quotaBytes});
 if(url.pathname==='/api/media'&&req.method==='POST'){
 const size=Number(req.headers['content-length']),type=String(req.headers['content-type']||'').split(';')[0],name=String(req.headers['x-file-name']||'Media').slice(0,200);if(!allowed.has(type))return reply(res,415,{error:'Unsupported media type.'});if(!Number.isSafeInteger(size)||size<12||size>maxBytes)return reply(res,413,{error:'Upload a media file up to 25 MB.'});if(uploads>=2)return reply(res,429,{error:'Two uploads are already in progress. Try again shortly.'});if(usage(wid)+size>quotaBytes)return reply(res,409,{error:'Workspace storage limit reached.'});if(db.prepare('SELECT COUNT(*) AS n FROM studio_media WHERE workspace_id=?').get(wid).n>=200)return reply(res,409,{error:'Workspace media limit reached.'});const id=randomUUID();db.prepare('INSERT INTO studio_media VALUES (?,?,?,?,?,?,?)').run(id,wid,name,type,size,'uploading',Date.now());uploads++;let handle;try{handle=await open(file(id),'wx',0o600);let count=0,head=Buffer.alloc(0);for await(const chunk of req){count+=chunk.length;if(count>size)throw Error('Upload exceeded declared size.');if(head.length<16)head=Buffer.concat([head,chunk]).subarray(0,16);await handle.writeFile(chunk);}if(count!==size||!validMedia(head,type))throw Error('File content does not match its media type.');await handle.close();handle=null;db.prepare("UPDATE studio_media SET state='ready' WHERE id=?").run(id);return reply(res,201,{asset:{id,name,type,size}});}catch(e){await handle?.close();await unlink(file(id)).catch(()=>{});db.prepare('DELETE FROM studio_media WHERE id=?').run(id);throw e;}finally{uploads--;}}
 if(url.pathname==='/api/media/import'&&req.method==='POST'){
 let text='';for await(const chunk of req){text+=chunk;if(text.length>1000)throw Error('Request too large.');}const {jobId}=JSON.parse(text);if(typeof jobId!=='string'||!uuid.test(jobId))throw Error('Choose a generation job.');const existing=db.prepare("SELECT m.id,m.name,m.type,m.size FROM studio_media_sources s JOIN studio_media m ON m.id=s.asset_id WHERE s.workspace_id=? AND s.job_id=? AND m.state='ready'").get(wid,jobId);if(existing)return reply(res,200,{asset:existing});const lock='import:'+wid+':'+jobId;if(locks.has(lock))return reply(res,409,{error:'This clip is already being saved.'});if(uploads>=2)return reply(res,429,{error:'Media transfers are busy.'});const job=db.prepare("SELECT result FROM studio_actions WHERE id=? AND workspace_id=? AND type IN ('video','image') AND status='completed'").get(jobId,wid);const result=job?.result?JSON.parse(job.result):null;if(!(result?.videoUrl||result?.imageUrl)||result.status!=='completed')throw Error('Check the completed generation status before saving it.');if(usage(wid)+maxBytes>quotaBytes)throw Error('Workspace storage limit reached.');const id=randomUUID();db.prepare('INSERT INTO studio_media VALUES (?,?,?,?,?,?,?)').run(id,wid,result.imageUrl?'Generated image':'Generated clip.mp4',result.imageUrl?'image/png':'video/mp4',maxBytes,'uploading',Date.now());uploads++;locks.add(lock);try{const downloaded=await downloader(result.videoUrl||result.imageUrl,file(id),maxBytes);if(!validMedia(downloaded.head,downloaded.type))throw Error('Provider returned invalid media.');db.prepare("UPDATE studio_media SET type=?,size=?,state='ready' WHERE id=?").run(downloaded.type,downloaded.size,id);db.prepare('INSERT INTO studio_media_sources VALUES (?,?,?) ON CONFLICT(workspace_id,job_id) DO UPDATE SET asset_id=excluded.asset_id').run(wid,jobId,id);return reply(res,201,{asset:{id,name:result.imageUrl?'Generated image':'Generated clip',type:downloaded.type,size:downloaded.size}});}catch(e){await unlink(file(id)).catch(()=>{});db.prepare('DELETE FROM studio_media WHERE id=?').run(id);throw e;}finally{uploads--;locks.delete(lock);}}
 if(url.pathname==='/api/media/exports/retry'&&req.method==='POST'){let text='';for await(const chunk of req){text+=chunk;if(text.length>1000)throw Error('Request too large.');}const {id}=JSON.parse(text);const job=db.prepare("SELECT * FROM studio_exports WHERE id=? AND workspace_id=?").get(String(id),wid);if(!job||job.state!=='failed')return reply(res,409,{error:'Only a failed export can be retried.'});if(db.prepare("SELECT COUNT(*) AS n FROM studio_exports WHERE state IN ('queued','running')").get().n>=10)return reply(res,429,{error:'Export queue is full.'});db.prepare("UPDATE studio_exports SET state='queued',error=NULL WHERE id=? AND workspace_id=?").run(job.id,wid);reply(res,202,{job:{...job,state:'queued',error:null}});void work();return;}
 if(url.pathname==='/api/media/exports'&&req.method==='GET')return reply(res,200,{jobs:db.prepare('SELECT * FROM studio_exports WHERE workspace_id=? ORDER BY created_at DESC LIMIT 50').all(wid)});
 if(url.pathname==='/api/media/exports'&&req.method==='POST'){let text='';for await(const chunk of req){text+=chunk;if(text.length>1000)throw Error('Request too large.');}const {sourceId}=JSON.parse(text);const source=db.prepare("SELECT * FROM studio_media WHERE id=? AND workspace_id=? AND state='ready'").get(String(sourceId),wid);if(!source||!['video/mp4','video/webm'].includes(source.type))return reply(res,400,{error:'Choose a saved MP4 or WebM video.'});let job=db.prepare('SELECT * FROM studio_exports WHERE source_id=? AND workspace_id=?').get(source.id,wid);if(!job){if(db.prepare("SELECT COUNT(*) AS n FROM studio_exports WHERE state IN ('queued','running')").get().n>=10)return reply(res,429,{error:'Export queue is full.'});const id=randomUUID();db.prepare('INSERT INTO studio_exports VALUES (?,?,?,?,?,?,?)').run(id,wid,source.id,'queued',null,null,Date.now());job=db.prepare('SELECT * FROM studio_exports WHERE id=?').get(id);}reply(res,202,{job});void work();return;}
 const match=url.pathname.match(/^\/api\/media\/([a-f0-9-]+)$/);if(!match||!uuid.test(match[1]))return reply(res,404,{error:'Media not found.'});const asset=db.prepare("SELECT * FROM studio_media WHERE id=? AND workspace_id=? AND state='ready'").get(match[1],wid);if(!asset)return reply(res,404,{error:'Media not found.'});
 if(req.method==='PATCH'){let text='';for await(const c of req){text+=c;if(text.length>4000)throw Error('Metadata is too large.');}const d=JSON.parse(text);if(typeof d.name!=='string'||!d.name.trim()||d.name.length>200||!Array.isArray(d.tags)||d.tags.length>10||d.tags.some(t=>typeof t!=='string'||!t.trim()||t.length>30)||typeof d.archived!=='boolean')throw Error('Enter a name, up to ten short tags and archive status.');const tags=[...new Set(d.tags.map(t=>t.trim()))];db.prepare('UPDATE studio_media SET name=? WHERE id=? AND workspace_id=?').run(d.name.trim(),asset.id,wid);db.prepare('INSERT INTO studio_media_metadata VALUES (?,?,?,?) ON CONFLICT(asset_id) DO UPDATE SET tags=excluded.tags,archived=excluded.archived').run(asset.id,wid,JSON.stringify(tags),d.archived?1:0);return reply(res,200,{asset:{...asset,name:d.name.trim(),tags,archived:d.archived}});}
 if(req.method==='DELETE'){for(const table of ['studio_documents','studio_brands']){if(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table)&&db.prepare('SELECT id FROM '+table+' WHERE workspace_id=? AND document LIKE ? LIMIT 1').get(wid,'%'+asset.id+'%'))return reply(res,409,{error:'This file is referenced by a saved project or brand. Detach it there first, or archive the file.'});}if(locks.has(asset.id)||db.prepare("SELECT id FROM studio_exports WHERE source_id=? AND state IN ('queued','running')").get(asset.id))return reply(res,409,{error:'This media is being used by an export.'});db.prepare('DELETE FROM studio_media WHERE id=? AND workspace_id=?').run(asset.id,wid);db.prepare('DELETE FROM studio_media_metadata WHERE asset_id=? AND workspace_id=?').run(asset.id,wid);await unlink(file(asset.id)).catch(()=>{});return reply(res,200,{removed:true});}
 if(!['GET','HEAD'].includes(req.method))return reply(res,405,{error:'Method not allowed.'});res.writeHead(200,{'Content-Type':asset.type,'Content-Length':asset.size,'Content-Disposition':'attachment; filename="media-'+asset.id+'"','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')return res.end();locks.add(asset.id);try{await pipeline(createReadStream(file(asset.id)),res);}finally{locks.delete(asset.id);}
 }catch(e){if(!res.headersSent)reply(res,400,{error:e.message||'Media action failed.'});else res.destroy();}}
 async function shareAsset(wid,id){if(new URL(origin).protocol!=='https:')throw Error('Reference generation requires a publicly reachable HTTPS studio URL.');const asset=db.prepare("SELECT id,type FROM studio_media WHERE id=? AND workspace_id=? AND state='ready'").get(String(id),wid);if(!asset||!asset.type.startsWith('image/'))throw Error('Reference image is not available in this workspace.');if(db.prepare('SELECT COUNT(*) AS n FROM studio_media_shares WHERE workspace_id=? AND expires_at>?').get(wid,Date.now()).n>=250)throw Error('Reference sharing limit reached. Wait for previous links to expire.');const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM studio_media_shares WHERE expires_at<?').run(Date.now());db.prepare('INSERT INTO studio_media_shares VALUES (?,?,?,?)').run(createHash('sha256').update(token).digest('hex'),wid,id,Date.now()+3600000);return origin+'/api/media/shared/'+token;}
 async function shared(req,res,url){if(!['GET','HEAD'].includes(req.method))return reply(res,405,{error:'Method not allowed.'});const token=url.pathname.slice('/api/media/shared/'.length);if(!/^[a-f0-9]{64}$/.test(token))return reply(res,404,{error:'Media link expired or unavailable.'});const asset=db.prepare("SELECT m.* FROM studio_media_shares s JOIN studio_media m ON m.id=s.asset_id AND m.workspace_id=s.workspace_id WHERE s.token_hash=? AND s.expires_at>? AND m.state='ready'").get(createHash('sha256').update(token).digest('hex'),Date.now());if(!asset)return reply(res,404,{error:'Media link expired or unavailable.'});res.writeHead(200,{'Content-Type':asset.type,'Content-Length':asset.size,'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')return res.end();await pipeline(createReadStream(file(asset.id)),res);}
 async function readReferenceAsset(wid,id,includeData=false){const asset=db.prepare("SELECT id,name,type,size FROM studio_media WHERE id=? AND workspace_id=? AND state='ready'").get(String(id),wid);if(!asset||!['image/png','image/jpeg','image/webp','video/mp4','video/webm'].includes(asset.type))throw Error('Reference is not available in this workspace.');if(!includeData)return asset;if(!asset.type.startsWith('image/')||asset.size>6*1048576)throw Error('Analysis requires images under 6 MB.');const bytes=await readFile(file(asset.id));return{...asset,dataUrl:'data:'+asset.type+';base64,'+bytes.toString('base64')};}
 return {handle,shareAsset,shared,readReferenceAsset,close:()=>{closed=true;clearInterval(timer);},work};
}
