import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
export type User={id:string;email:string};
type Auth={user:User|null;loading:boolean;available:boolean;emailEnabled:boolean;testMode:boolean;refresh:()=>Promise<void>;signOut:()=>Promise<void>};
const Context=createContext<Auth>({user:null,loading:true,available:false,emailEnabled:false,testMode:false,refresh:async()=>{},signOut:async()=>{}});
export async function request<T>(url:string,options:RequestInit={}):Promise<T>{const r=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});let data;try{data=await r.json();}catch{throw Error('The account server is unavailable. Try again shortly.');}if(!r.ok)throw Object.assign(Error(data.error?.message||data.error||data.message||'The request could not be completed.'),{status:r.status});return data as T;}
export function AccountProvider({children}:{children:ReactNode}){const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[available,setAvailable]=useState(false),[settings,setSettings]=useState({email:false,testMode:false});async function refresh(){try{const c=await request<{auth:{email:boolean;testMode:boolean}}>('/api/config');setAvailable(true);setSettings(c.auth);try{const s=await request<{user:User}>('/api/session');setUser(s.user);}catch(e){setUser(null);if((e as {status?:number}).status!==401)throw e;}}catch{setAvailable(false);}finally{setLoading(false);}}useEffect(()=>{void refresh();},[]);async function signOut(){await request('/api/auth/sign-out',{method:'POST',body:'{}'});setUser(null);sessionStorage.removeItem('story-unsaved');for(const key of Object.keys(sessionStorage))if(key.startsWith('production-script:'))sessionStorage.removeItem(key);location.assign('/');}return <Context.Provider value={{user,loading,available,emailEnabled:settings.email,testMode:settings.testMode,refresh,signOut}}>{children}</Context.Provider>;}
export const useAccount=()=>useContext(Context);
export type Planner={characterId:string;minutes:number;kind:'cast'|'new'|'upload';characterUrl:string;characterName:string;styleUrl:string;voiceName:string};
export type Draft={id:string;revision:number;updatedAt:number;title:string;idea:string;language:string;style:string;voiceId:string;planner?:Planner;[key:string]:unknown};
export function cleanDocument(d:Draft){const {id,revision,createdAt,updatedAt,batchId,...document}=d;void id;void revision;void createdAt;void updatedAt;void batchId;return document;}
